version: '3'
services:
  jenkins:
    image: jenkins/jenkins:latest
    volumes:
      - ~/temp-jenkins:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    ports:
      - 8080:8080
      - 50000:50000
    restart: unless-stopped
